### ISSUE TITLE
Program size is way too high

### ISSUE THREAD

**Issue by baleksey** [glumb/mrc#2]
Hi,

I've tried to run your library on my UNO and it says that program size (70250 bytes) is way too high then I can handle (32kb). 
Is it possible to reduce it to 32kb or I need to buy another arduino version?

P.S. Even Teensy 3.1 won't fit your lib with it 64kb and you mentioned it in .ini file.

**Comment by glumb** [comment]
I was using a Uno myself but eventually switched to a Teensy 3.2 because of the program size.
You can try to remove the `Display.h` and all references to it in `main.h` but I assume the code is still over 32kb. Also it is possible to only use the `RobotController.h/cpp`, `VarSpeedServo` and `Kinematic` if you do not need the serial communication
In the ini teensy31 is given, since Teensy 3.1 and 3.2 use the same identifier http://docs.platformio.org/en/latest/platforms/teensy.html
